import { spawn, type ChildProcess } from "node:child_process";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import type {
  IntegrationRunRequest,
  IntegrationRunResult,
  IntegrationTestFile,
  PlaywrightSetupResult,
  PlaywrightStatus,
} from "../shared/api";
import { detectPreview } from "./devServer";
import { projectRoot, storyIdFromSpecFilename } from "./utils";

// ---------------------------------------------------------------------------
// Playwright runner: sets up @playwright/test inside the *generated* project
// (dependency, config with baseURL/webServer, chromium) and runs the
// integration specs under tests/integration with live streamed output.

const OUTPUT_TAIL_MAX = 8000;
const INSTALL_TIMEOUT_MS = 10 * 60_000;
const RUN_TIMEOUT_MS = 10 * 60_000;

const CONFIG_NAMES = [
  "playwright.config.ts",
  "playwright.config.js",
  "playwright.config.mjs",
  "playwright.config.cjs",
];

let listener: ((data: { text: string }) => void) | null = null;
let activeChild: ChildProcess | null = null;
let stopRequested = false;

export function onIntegrationOutput(cb: (data: { text: string }) => void): () => void {
  listener = cb;
  return () => {
    if (listener === cb) listener = null;
  };
}

function emit(text: string): void {
  listener?.({ text });
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function hasPlaywrightDep(root: string): Promise<boolean> {
  try {
    const raw = await fs.readFile(path.join(root, "package.json"), "utf8");
    const pkg = JSON.parse(raw) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    if (pkg.dependencies?.["@playwright/test"] || pkg.devDependencies?.["@playwright/test"]) {
      return true;
    }
  } catch {
    // no package.json — fall through to node_modules check
  }
  return exists(path.join(root, "node_modules", "@playwright", "test"));
}

async function findConfig(root: string): Promise<boolean> {
  for (const name of CONFIG_NAMES) {
    if (await exists(path.join(root, name))) return true;
  }
  return false;
}

async function listTestFiles(root: string): Promise<IntegrationTestFile[]> {
  const dir = path.join(root, "tests", "integration");
  const out: IntegrationTestFile[] = [];
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const e of entries) {
      if (!e.isFile() || !/\.spec\.(ts|tsx|js|jsx)$/.test(e.name)) continue;
      out.push({
        path: path.posix.join("tests", "integration", e.name),
        storyId: storyIdFromSpecFilename(e.name),
      });
    }
  } catch {
    // tests/integration may not exist yet
  }
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

export async function getPlaywrightStatus(specPath: string): Promise<PlaywrightStatus> {
  const root = projectRoot(specPath);
  return {
    installed: await hasPlaywrightDep(root),
    configPresent: await findConfig(root),
    testFiles: await listTestFiles(root),
  };
}

function playwrightConfigSource(baseURL: string, devCommand?: string): string {
  const webServer = devCommand
    ? `
  // Playwright starts the app for you (and reuses one that is already running,
  // e.g. the SpecOps preview tab).
  webServer: {
    command: ${JSON.stringify(devCommand)},
    url: ${JSON.stringify(baseURL)},
    reuseExistingServer: true,
    timeout: 120_000,
  },`
    : "";
  return `import { defineConfig } from "@playwright/test";

// Generated by SpecOps — adjust baseURL/webServer to match your app.
export default defineConfig({
  testDir: "./tests/integration",
  timeout: 30_000,
  use: {
    baseURL: ${JSON.stringify(baseURL)},
    headless: true,
    screenshot: "only-on-failure",
    trace: "retain-on-failure",
  },${webServer}
});
`;
}

interface CommandOutcome {
  code: number;
  output: string;
}

// Run a shell command with output streamed to the renderer; the returned
// output is a tail capped at OUTPUT_TAIL_MAX.
function runStreaming(cmd: string, cwd: string, timeoutMs: number): Promise<CommandOutcome> {
  return new Promise((resolve) => {
    emit(`$ ${cmd}\n`);
    const child = spawn(cmd, {
      cwd,
      shell: true,
      env: { ...process.env, FORCE_COLOR: "0", NO_COLOR: "1" },
    });
    activeChild = child;
    let output = "";
    let settled = false;

    const timer = setTimeout(() => {
      emit(`\n(timed out after ${Math.round(timeoutMs / 1000)}s — killing)\n`);
      try {
        child.kill("SIGKILL");
      } catch {
        // already gone
      }
    }, timeoutMs);

    const onChunk = (chunk: Buffer): void => {
      const text = chunk.toString("utf8");
      output = (output + text).slice(-OUTPUT_TAIL_MAX);
      emit(text);
    };
    child.stdout?.on("data", onChunk);
    child.stderr?.on("data", onChunk);

    const settle = (code: number): void => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (activeChild === child) activeChild = null;
      resolve({ code, output });
    };
    child.on("error", (err) => {
      emit(`\n${err.message}\n`);
      output = (output + err.message).slice(-OUTPUT_TAIL_MAX);
      settle(1);
    });
    child.on("exit", (code) => settle(code ?? 1));
  });
}

export function stopIntegrationRun(): void {
  stopRequested = true;
  const child = activeChild;
  if (child && child.exitCode === null) {
    try {
      child.kill("SIGTERM");
    } catch {
      // already gone
    }
  }
}

export async function setupPlaywright(specPath: string): Promise<PlaywrightSetupResult> {
  const root = projectRoot(specPath);
  const logs: string[] = [];
  stopRequested = false;

  const step = async (cmd: string): Promise<CommandOutcome> => {
    const res = await runStreaming(cmd, root, INSTALL_TIMEOUT_MS);
    logs.push(`$ ${cmd}\n${res.output}`);
    return res;
  };

  try {
    if (!(await exists(path.join(root, "package.json")))) {
      const init = await step("npm init -y");
      if (init.code !== 0) throw new Error("npm init failed — see log");
    }
    if (!(await hasPlaywrightDep(root))) {
      const install = await step("npm install --save-dev @playwright/test");
      if (install.code !== 0) throw new Error("npm install @playwright/test failed — see log");
    }
    if (!(await findConfig(root))) {
      const info = await detectPreview(specPath);
      const baseURL =
        info.url && info.url.startsWith("http") ? info.url : "http://localhost:3000";
      const configPath = path.join(root, "playwright.config.ts");
      await fs.writeFile(configPath, playwrightConfigSource(baseURL, info.command), "utf8");
      const note = `wrote playwright.config.ts (baseURL ${baseURL}${info.command ? `, webServer "${info.command}"` : ""})\n`;
      emit(note);
      logs.push(note);
    }
    // Downloads chromium on first run; a no-op when it is already present.
    const browsers = await step("npx playwright install chromium");
    if (browsers.code !== 0) throw new Error("playwright install chromium failed — see log");

    return { status: await getPlaywrightStatus(specPath), log: logs.join("\n") };
  } catch (err) {
    return {
      status: await getPlaywrightStatus(specPath),
      log: logs.join("\n"),
      error: stopRequested ? "setup stopped by user" : (err as Error).message,
    };
  }
}

const MISSING_BROWSER_RE = /playwright install|Executable doesn't exist/i;

export async function runIntegrationTests(
  req: IntegrationRunRequest,
): Promise<IntegrationRunResult> {
  if (activeChild) {
    return {
      file: req.file,
      passed: false,
      exitCode: 1,
      output: "",
      duration: 0,
      error: "a Playwright run is already in progress",
    };
  }
  const root = projectRoot(req.specPath);
  const target = req.file ? `"${req.file}"` : "tests/integration";
  const cmd = `npx --yes playwright test ${target} --reporter=line`;
  stopRequested = false;

  const start = Date.now();
  try {
    let res = await runStreaming(cmd, root, RUN_TIMEOUT_MS);

    // Self-heal the classic first-run failure: browsers not downloaded yet.
    if (res.code !== 0 && !stopRequested && MISSING_BROWSER_RE.test(res.output)) {
      emit("\nBrowsers missing — running `npx playwright install chromium` and retrying…\n");
      const install = await runStreaming("npx playwright install chromium", root, INSTALL_TIMEOUT_MS);
      if (install.code === 0 && !stopRequested) {
        res = await runStreaming(cmd, root, RUN_TIMEOUT_MS);
      }
    }

    return {
      file: req.file,
      passed: res.code === 0,
      exitCode: res.code,
      output: res.output,
      duration: Date.now() - start,
      error: stopRequested ? "stopped by user" : undefined,
    };
  } catch (err) {
    return {
      file: req.file,
      passed: false,
      exitCode: 1,
      output: "",
      duration: Date.now() - start,
      error: (err as Error).message,
    };
  }
}
